name: PrepareRelease
on:
  push:
    branches:
      - release
jobs:
  CalculateVersion:
    runs-on: ubuntu-latest
    outputs:
      release_version: ${{steps.tag_version.outputs.new_version}}
    steps:
      - uses: actions/checkout@v3
      - name: Calculate Bump version
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true
          release_branches: "release"
  VersionUpCommit:
    runs-on: ubuntu-latest
    name: Commit new version
    needs: CalculateVersion
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install toolchain
        run: rustup set profile default
      - name: Install cargo-edit
        run: cargo install cargo-edit
      - name: set version
        id: set_version
        continue-on-error: true
        run: |
          cargo set-version ${{needs.CalculateVersion.outputs.release_version}}
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m 'Bump version to ${{ inputs.version }}'
          git push origin 'release'
      - name: Create Pull Request
        uses: actions/github-script@v6
        if: steps.set_version.outcome == 'success'
        with:
          script: |
            const response = await github.rest.pulls.create({
              title: 'Bump version to ${{needs.CalculateVersion.outputs.release_version}}',
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: 'release',
              base: 'master',
              body: '### What\nBump version to ${{ inputs.version }}, creating release branch.\n\n### Why\nTriggered by @${{ github.actor }} in ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}.'
            });
            return response.data.number;
